import { cardIcon, earlyBirdsIcon, newsletterIcon, welcomeIcon } from "@/icons/icons";

export const publicEvent = [
  {
    id: 1,
    title: "Signature Cultural Programs by Qatar Creates",
    category: "Culinary",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    description: "Description for Public Event 1",
    location: "Lynx Tower, Doha. Qatar 1",
  },
  {
    id: 2,
    title: "Signature Cultural Programs by Qatar Creates 2",
    category: "Culinary",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    description: "Description for Public Event 2",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 3,
    title: "Signature Cultural Programs by Qatar Creates 3",
    category: "Culinary",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    description: "Description for Public Event 2",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 4,
    title: "Signature Cultural Programs by Qatar Creates 4",
    category: "Culinary",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    description: "Description for Public Event 2",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 5,
    title: "Signature Cultural Programs by Qatar Creates 5",
    category: "Culinary",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    description: "Description for Public Event 2",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 6,
    title: "Signature Cultural Programs by Qatar Creates 6",
    category: "Culinary",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    description: "Description for Public Event 2",
    location: "Lynx Tower, Doha. Qatar 2",
  },
];

export const sortOption = [
  "Date: Newest to Oldest",
  "Date: Oldest to Newest",
  "Alphabetical: A-Z",
  "Alphabetical: Z-A",
  "Author: A - Z",
  "Author: Z - A",
];

export const issueType = [
  "Membership Support",
  "partnering & Sponsorship",
  "Technical Support",
  "Other",
];

export const membershipTire = ["Option A", "Option B", "Test", "Other"];

export const faqList = [
  {
    question: "Can I upgrade my membership?",
    answer:
      "Yes. You can upgrade anytime. Your new tier starts immediately, and the unused value of your current membership will be credited toward the upgrade.",
  },
  {
    question: "Can I cancel my membership?",
    answer: "Click on the Sign Up button and fill in your details.",
  },
  {
    question: "Can I downgrade?",
    answer: "No, our platform is free to use.",
  },
  {
    question: "Can I share my membership?",
    answer: "No, our platform is free to use.",
  },
  {
    question: "How do I renew my membership?",
    answer: "No, our platform is free to use.",
  },
  {
    question: "Can I add a family member to Explorer?",
    answer: "No, our platform is free to use.",
  },
  {
    question: "Who do I reach out to for support?",
    answer: "No, our platform is free to use.",
  },
];

export const scheduleEvent = [
  {
    id: 1,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
  {
    id: 2,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
  {
    id: 3,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
  {
    id: 4,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
  {
    id: 5,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
  {
    id: 6,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
  {
    id: 7,
    title: "Qatar International Food Festival",
    date: "18 - September 2025",
    category: "Architecture & Urban",
  },
];

export const upcomingEvent = [
  {
    id: 1,
    type: "Public Event",
    title: "Developing Your Vision: Documentary & Storytelling",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 2,
    type: "Public Event",
    title: "Fashion as a Cultural Language",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 3,
    type: "Public Event",
    title: "The Business of Creativity in Qatar",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 4,
    type: "Public Event",
    title: "The Power of Storytelling in the Gulf",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 5,
    type: "Public Event",
    title: "The Power of Storytelling in the Gulf",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 6,
    type: "Public Event",
    title: "The Power of Storytelling in the Gulf",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
  {
    id: 7,
    type: "Public Event",
    title: "The Power of Storytelling in the Gulf",
    date: "21 Jun, 2025 - 19:00 - 19:30",
    category: "Architecture & Urban",
    location: "Lynx Tower, Doha. Qatar 2",
  },
];

export const InsiderBenefits = [
  {
    id: 1,
    title: "Insider",
    description: "Great for individual person",
    membershipFor: [
      "Individual, age 20",
      "Culturally curious",
      "Exclusive, meaningful experiences",
      "Build community connections",
    ],
    price: 250,
    benefitlist: [
      "Digital Membership Card",
      "Welcome Gift (50 QAR)",
      "Monthly Insider Newsletter",
      "Join Insider Networking Hubs",
      "Invitations to Curated Events",
      "Insider Networking Sessions",
      "Family Day & Seasonal Events",
      "Member-Only Previews",
      "10% Retail Discount",
      "Access Culinary Events",
      "Chef-in-Residence Invitation",
      "Partner Affiliate Discounts",
      "Creative Workspace Access",
      "Knowledge Exchange Access",
      "Trade Fair & Exhibition Access",
    ],
  },
  {
    id: 2,
    title: "Catalyst",
    description: "Great for artists, artisans, teachers",
    price: 200,
    membershipFor: [
      "Individual, age 20",
      "Fun, interactive, educational experiences",
      "Grow cultural engagement",
    ],
    benefitlist: [
      "Digital Membership Card",
      "Welcome Gift (50 QAR)",
      "Monthly Insider Newsletter",
      "Join Insider Networking Hubs",
      "Invitations to Curated Events",
      "Insider Networking Sessions",
      "Family Day & Seasonal Events",
      "Member-Only Previews",
      "10% Retail Discount",
      "Access Culinary Events",
      "Chef-in-Residence Invitation",
      "Partner Affiliate Discounts",
      "Creative Workspace Access",
      "Knowledge Exchange Access",
      "Trade Fair & Exhibition Access",
    ],
  },
  {
    id: 3,
    title: "Explorers",
    description: "Great for family member",
    price: 500,
    membershipFor: [
      "Families: 2 adults + up to 4 children",
      "Children are below the age of 19",
      "Can add additional adult & children",
      "Build community connections",
    ],
    benefitlist: [
      "Digital Membership Card",
      "Welcome Gift (50 QAR)",
      "Monthly Insider Newsletter",
      "Join Insider Networking Hubs",
      "Invitations to Curated Events",
      "Insider Networking Sessions",
      "Family Day & Seasonal Events",
      "Member-Only Previews",
      "10% Retail Discount",
      "Access Culinary Events",
      "Chef-in-Residence Invitation",
      "Partner Affiliate Discounts",
      "Creative Workspace Access",
      "Knowledge Exchange Access",
      "Trade Fair & Exhibition Access",
    ],
  },
  {
    id: 4,
    title: "Patron",
    description: "Great for family member",
    price: 500,
    membershipFor: [
      "Families: 2 adults + up to 4 children",
      "Children are below the age of 19",
      "Can add additional adult & children",
      "Build community connections",
    ],
    benefitlist: [
      "Digital Membership Card",
      "Welcome Gift (50 QAR)",
      "Monthly Insider Newsletter",
      "Join Insider Networking Hubs",
      "Invitations to Curated Events",
      "Insider Networking Sessions",
      "Family Day & Seasonal Events",
      "Member-Only Previews",
      "10% Retail Discount",
      "Access Culinary Events",
      "Chef-in-Residence Invitation",
      "Partner Affiliate Discounts",
      "Creative Workspace Access",
      "Knowledge Exchange Access",
      "Trade Fair & Exhibition Access",
    ],
  },
  {
    id: 5,
    title: "Seeker",
    description: "Great for family member",
    price: 500,
    membershipFor: [
      "Families: 2 adults + up to 4 children",
      "Children are below the age of 19",
      "Can add additional adult & children",
      "Build community connections",
    ],
    benefitlist: [
      "Digital Membership Card",
      "Welcome Gift (50 QAR)",
      "Monthly Insider Newsletter",
      "Join Insider Networking Hubs",
      "Invitations to Curated Events",
      "Insider Networking Sessions",
      "Family Day & Seasonal Events",
      "Member-Only Previews",
      "10% Retail Discount",
      "Access Culinary Events",
      "Chef-in-Residence Invitation",
      "Partner Affiliate Discounts",
      "Creative Workspace Access",
      "Knowledge Exchange Access",
      "Trade Fair & Exhibition Access",
    ],
  },
];

export const countryDialCodes = [
  { code: "+1", country: "United States / Canada" },
  { code: "+7", country: "Russia / Kazakhstan" },
  { code: "+20", country: "Egypt" },
  { code: "+27", country: "South Africa" },
  { code: "+30", country: "Greece" },
  { code: "+31", country: "Netherlands" },
  { code: "+32", country: "Belgium" },
  { code: "+33", country: "France" },
  { code: "+34", country: "Spain" },
  { code: "+39", country: "Italy" },
  { code: "+40", country: "Romania" },
  { code: "+41", country: "Switzerland" },
  { code: "+44", country: "United Kingdom" },
  { code: "+45", country: "Denmark" },
  { code: "+46", country: "Sweden" },
  { code: "+47", country: "Norway" },
  { code: "+48", country: "Poland" },
  { code: "+49", country: "Germany" },
  { code: "+52", country: "Mexico" },
  { code: "+55", country: "Brazil" },
  { code: "+61", country: "Australia" },
  { code: "+62", country: "Indonesia" },
  { code: "+63", country: "Philippines" },
  { code: "+64", country: "New Zealand" },
  { code: "+65", country: "Singapore" },
  { code: "+66", country: "Thailand" },
  { code: "+81", country: "Japan" },
  { code: "+82", country: "South Korea" },
  { code: "+84", country: "Vietnam" },
  { code: "+86", country: "China" },
  { code: "+90", country: "Turkey" },
  { code: "+91", country: "India" },
  { code: "+92", country: "Pakistan" },
  { code: "+93", country: "Afghanistan" },
  { code: "+94", country: "Sri Lanka" },
  { code: "+95", country: "Myanmar" },
  { code: "+98", country: "Iran" },
  { code: "+211", country: "South Sudan" },
  { code: "+212", country: "Morocco" },
  { code: "+213", country: "Algeria" },
  { code: "+216", country: "Tunisia" },
  { code: "+218", country: "Libya" },
  { code: "+220", country: "Gambia" },
  { code: "+221", country: "Senegal" },
  { code: "+234", country: "Nigeria" },
  { code: "+251", country: "Ethiopia" },
  { code: "+254", country: "Kenya" },
  { code: "+255", country: "Tanzania" },
  { code: "+256", country: "Uganda" },
  { code: "+260", country: "Zambia" },
  { code: "+263", country: "Zimbabwe" },
  { code: "+354", country: "Iceland" },
  { code: "+358", country: "Finland" },
  { code: "+380", country: "Ukraine" },
  { code: "+420", country: "Czech Republic" },
  { code: "+421", country: "Slovakia" },
  { code: "+852", country: "Hong Kong" },
  { code: "+853", country: "Macau" },
  { code: "+855", country: "Cambodia" },
  { code: "+856", country: "Laos" },
  { code: "+880", country: "Bangladesh" },
  { code: "+961", country: "Lebanon" },
  { code: "+962", country: "Jordan" },
  { code: "+963", country: "Syria" },
  { code: "+964", country: "Iraq" },
  { code: "+965", country: "Kuwait" },
  { code: "+966", country: "Saudi Arabia" },
  { code: "+971", country: "United Arab Emirates" },
  { code: "+972", country: "Israel" },
  { code: "+973", country: "Bahrain" },
  { code: "+974", country: "Qatar" },
  { code: "+975", country: "Bhutan" },
  { code: "+976", country: "Mongolia" },
  { code: "+977", country: "Nepal" },
];

export const benefitsList = [
  {
    id: 1,
    title: "Digital Membership Card",
    description:
      "Instantly access your membership with your e-card from the dashboard or email.",
    icon: cardIcon(),
    buttonText: "Add to Wallet",
    badges:[ "ONE PER MEMBERSHIP", "INCLUDED" ]
  },
  {
    id: 2,
    title: "WELCOME GIFT (50 QAR)",
    description:
      "Claim your one-time welcome gift worth up to 50 QAR using your Flash e-card.",
    icon: welcomeIcon(),
    buttonText: "Redeem Gift",
    badges:[ "One-time redeem" ]
  },
  {
    id: 3,
    title: "Early Bird Tickets",
    description:
      "Enjoy priority booking for Qatar Creates events before they go public.",
    icon: earlyBirdsIcon(),
    buttonText: "View Events",
    badges:[ "All year round", "Priority booking"]
  },
  {
    id: 4,
    title: "Monthly Insider Newsletter",
    description:
      "Get cultural updates, upcoming events, and special member-only news in your inbox every month.",
    icon: newsletterIcon(),
    buttonText: "Read Latest Issue",
    badges:[ "Monthly", "Insider Updates"]
  },
]