import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

import ApolloWrapper from "@/lib/apollo-provider";
import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import TopNav from "@/components/layout/user-portal/TopNav";
import SidebarMenu from "@/components/layout/user-portal/SidebarMenu";

interface Props {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  // Load translation file directly in the layout
  let messages;
  try {
    messages = (await import(`../locales/${locale}.json`)).default;
  } catch {
    messages = {}; // fallback if translation not found
  }

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ApolloWrapper>
            <div className="flex min-h-screen w-full overflow-x-hidden">
              {/* Sidebar fixed on the left */}
              <aside className="w-72 fixed inset-y-0 left-0 z-30 bg-white border-r shadow-sm">
                <SidebarMenu />
              </aside>
              {/* Main content area shifted right by sidebar width */}

              <div className="flex-1 ml-72 min-h-screen bg-page-main">
                <div className="w-full">
                  <TopNav />
                </div>
                <main className="bg-page-main min-h-[1300px] p-6">
                  {children}
                </main>
              </div>
              {/* <nav className="w-full bg-white shadow-md px-4 py-2 flex items-center">
 
 <div className="flex-1 max-w-xs sm:max-w-sm md:max-w-md">
   <input 
     type="text"
     placeholder="Search..."
     className="w-full px-3 py-2 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
   />
 </div>

 
 <div className="ml-auto flex-shrink-0 text-black">
   dfdsgdgfdfdg
 </div>
</nav> */}

</div>
              {/* <div className="flex-1 ml-72">
                <div className="bg-page-main">
                  <TopNav />
                </div>
                <main className="bg-page-main min-h-[1300px]">
                  {children}
                </main>
              </div> */}
            

            {/* <div className="flex flex-row">
              <div>
                <SidebarMenu />
              </div>
                <div className="w-full h-auto min-h-[1300px] bg-page-main">
                <div className="w-full">
                  <TopNav />
                </div>
                <div>
                {children}
                </div>
              </div>
            </div> */}
          </ApolloWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
