import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import ApolloWrapper from "@/lib/apollo-provider";
import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import LeftsideSection from "./LeftsideSection/LeftsideSection";
import "@/app/globals.css";

interface Props {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  // Load translation file directly in the layout
  let messages;
  try {
    messages = (await import(`../locales/${locale}.json`)).default;
  } catch {
    messages = {}; // fallback if translation not found
  }

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ApolloWrapper>
            <div className="w-full h-[auto] bg-Background-White inline-flex justify-start items-center">
              <LeftsideSection />
              <div className="w-3/4 inline-flex flex-col justify-start items-center overflow-hidden">
                {children}
              </div>
            </div>
          </ApolloWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
