import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import ApolloWrapper from "@/lib/apollo-provider";
import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";
import TopNav from "@/components/layout/user-portal/TopNav";
import SidebarMenu from "@/components/layout/user-portal/SidebarMenu";

interface Props {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  // Load translation file directly in the layout
  let messages;
  try {
    messages = (await import(`../locales/${locale}.json`)).default;
  } catch {
    messages = {}; // fallback if translation not found
  }

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ApolloWrapper>

            <div className="flex flex-row">
              <div>
                <SidebarMenu />
              </div>
              <div className="w-full bg-page-main">
                <div className="w-full">
                  <TopNav />
                </div>
                <div>
                {children}
                </div>
              </div>
            </div>
          </ApolloWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
